/**
 * Renders the page templates in src/pages into one static tree per text
 * variant (es/, granaino/), plus 404.html and the redirects that keep the old
 * /gd/ URLs working.
 *
 * Templates are the pages' markup with placeholders:
 *   {{t:key}}   the variant's text for `key` in i18n/translations.csv
 *   {{v}}       the variant being rendered (es | granaino), for internal links
 *   {{alt}}     the other variant, and {{route}} the page's route (/biografia)
 *   {{switch}}  src/partials/lang-switch.html
 *
 * An empty cell falls back to the es text, so a new row only needs the
 * Spanish column to build. Everything under es/, granaino/ and gd/ is
 * generated: edit the templates and the CSV, never the output.
 *
 * Usage: node scripts/build-i18n.mjs [--check]
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, globSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';
import {
  VARIANTS, DEFAULT_VARIANT, LEGACY_PREFIXES, TRANSLATIONS,
  listTemplates, readTranslations, outputPath
} from './lib/site.mjs';

const CHECK_ONLY = process.argv.includes('--check');

const SWITCH = readFileSync('src/partials/lang-switch.html', 'utf8').trim();
const strings = readTranslations();
const usedKeys = new Set();
const errors = [];

const banner = (source) =>
  `<!-- Generated by scripts/build-i18n.mjs from ${source} and ${TRANSLATIONS}. Edit those, not this file. -->`;

function render(template, variant) {
  const alt = VARIANTS[(VARIANTS.indexOf(variant) + 1) % VARIANTS.length];
  let out = template.body.replaceAll('{{switch}}', SWITCH);

  out = out.replace(/\{\{t:([\w.-]+)\}\}/g, (placeholder, key) => {
    const entry = strings.get(key);
    if (!entry) {
      errors.push(`${template.file}: no row "${key}" in ${TRANSLATIONS}`);
      return placeholder;
    }
    usedKeys.add(key);
    const text = entry[variant] || entry[DEFAULT_VARIANT];
    if (!text) errors.push(`${TRANSLATIONS}: "${key}" has no ${DEFAULT_VARIANT} text`);
    return text;
  });

  out = out
    .replaceAll('{{v}}', variant)
    .replaceAll('{{alt}}', alt)
    .replaceAll('{{route}}', template.route);

  const leftover = out.match(/\{\{[^}]*\}\}/);
  if (leftover) errors.push(`${template.file} (${variant}): unresolved ${leftover[0]}`);

  return out.replace(/^(<!DOCTYPE html>)/i, `$1${banner(template.file)}`);
}

/** A page at a retired URL that sends visitors and crawlers to its new home. */
function redirect(target) {
  return [
    '<!DOCTYPE html>',
    `${banner('scripts/build-i18n.mjs')}`,
    '<html lang="es"><head><meta charset="utf-8"/>',
    '<title>Charanga Ponte Una Milnoh</title>',
    '<meta name="robots" content="noindex"/>',
    `<link rel="canonical" href="${target}"/>`,
    `<meta http-equiv="refresh" content="0; url=${target}"/>`,
    `<script>location.replace('${target}' + location.hash);</script>`,
    `</head><body><a href="${target}">${target}</a></body></html>`,
    ''
  ].join('\n');
}

/** path -> expected content */
const outputs = new Map();

for (const template of listTemplates()) {
  for (const variant of template.variants) {
    const html = render(template, variant);
    if (html.includes('class="lang-switch"') && template.variants.length < VARIANTS.length) {
      errors.push(`${template.file}: {{switch}} on a page that only exists in ${template.variants.join(', ')}`);
    }
    outputs.set(outputPath(variant, template.slug), html);
    if (variant === DEFAULT_VARIANT && template.slug === '404') outputs.set('404.html', html);
  }
  for (const [legacy, variant] of Object.entries(LEGACY_PREFIXES)) {
    if (template.variants.includes(variant)) {
      outputs.set(outputPath(legacy, template.slug), redirect(`/${variant}${template.route}`));
    }
  }
}

for (const key of strings.keys()) {
  if (!usedKeys.has(key)) console.warn(`warning: ${TRANSLATIONS}: "${key}" is not used by any template`);
}
if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}

// Pages left over from a template that no longer exists.
const generatedDirs = [...VARIANTS, ...Object.keys(LEGACY_PREFIXES)];
const stale = globSync(generatedDirs.map((d) => `${d}/**/index.html`))
  .map((p) => p.split('\\').join('/'))
  .filter((p) => !outputs.has(p));

let changed = 0;
for (const [path, html] of outputs) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === html) continue;
  changed++;
  if (CHECK_ONLY) {
    console.log(`out of date: ${path}`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, html, 'utf8');
  }
}
for (const path of stale) {
  console.log(`${CHECK_ONLY ? 'stale' : 'removed'}: ${path}`);
  if (!CHECK_ONLY) rmSync(path);
}

console.log(`${outputs.size} pages, ${changed + stale.length} ${CHECK_ONLY ? 'out of date' : 'written or removed'}`);
if (CHECK_ONLY && changed + stale.length) process.exit(1);
